### ISSUE TITLE
Unicode in names of notebooks

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/JuliaBox#296]
Trying to create a notebook with a unicode character in the name gives a (cryptic) error:

```
Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/IPython/html/base/handlers.py", line 441, in wrapper result = yield gen.maybe_future(method(self, *args, **kwargs)) File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run value = future.result() File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper yielded = next(result) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/handlers.py", line 144, in patch model = yield gen.maybe_future(cm.update(model, path)) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/manager.py", line 245, in update self.rename(path, new_path) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/manager.py", line 233, in rename self.rename_file(old_path, new_path) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/filemanager.py", line 452, in rename_file if os.path.exists(new_os_path): File "/usr/lib/python2.7/genericpath.py", line 18, in exists os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 24: ordinal not in range(128)
```

Worse, I made a notebook with accents in the title (in Spanish), and this led to a similar cryptic error after a `git pull` from within JuliaBox.

The error message shows that it is using Python 2.7. Perhaps changing to Python 3 would solve this?

**Comment by luchr** [comment]
The source of the problem is: IPython in JB uses ASCII as default system encoding (at the time of writing this). See (in a Python2-Kernel-based notebook) the output of

```
import sys
sys.getdefaultencoding()
```
That's the reason why Python2 cannot decode the name. [Python 3 handles this all differently; no problem there.]

The more deeper reason is that Python2's `os.listdir` spits out byte-strings (even if the input-argument is a unicode-string) for the entries that it cannot handle with the sys.getdefaultencoding(). See output of

```
import os
os.listdir(u".")
```
and then you see in the list unicode-strings *and* bytestrings if there are dir-entries that cannot be decoded to unicode-strings.

But I have no idea how to change the default encoding (or the default locale for the User "juser" from "POSIX" to "C.UTF-8") inside juliabox.
