### ISSUE TITLE
Login failing in custom JuliaBox

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/JuliaBox#392]
A custom juliabox install has started failing to start an instance through google oauth, giving the following error in `JuliaBox/engine/logs/enginedaemon_err.log ` 

```
2016-05-26 20:51:35,852 - ERROR - juliabox.srvr_jboxd.JBoxd - Exception in jboxd_method launch_session
Traceback (most recent call last):
  File "/jboxengine/src/juliabox/srvr_jboxd.py", line 24, in wrapper
    f(*args, **kwargs)
  File "/jboxengine/src/juliabox/srvr_jboxd.py", line 125, in launch_session
    SessContainer.launch_by_name(name, email, reuse=reuse)
  File "/jboxengine/src/juliabox/interactive/sess_container.py", line 110, in launch_by_name
    cont = SessContainer._create_new(name, email)
  File "/jboxengine/src/juliabox/interactive/sess_container.py", line 59, in _create_new
    pkgs_disk = VolMgr.get_pkg_mount_for_user(email)
  File "/jboxengine/src/juliabox/vol/volmgr.py", line 132, in get_pkg_mount_for_user
    disk = plugin.get_disk_for_user(email)
  File "/jboxengine/src/juliabox/plugins/vol_defpkg/defpkg.py", line 61, in get_disk_for_user
    disk_path = os.path.join(JBoxDefaultPackagesVol.FS_LOC, JBoxDefaultPackagesVol.CURRENT_BUNDLE)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

It appears to be an error with `JBoxDefaultPackagesVol.CURRENT_BUNDLE` not being set after being initialized as None type

**Comment by ianshmean** [comment]
The issue persists after a fresh install (after removing docker, and deleting directories /jboxengine and ~/JuliaBox)

**Comment by ianshmean** [comment]
For no apparent reason, login just started working without the above errors...

I've seen this sporadic behaviour before but never linked it to the above error. It may be a recurring issue on my install

**Comment by tanmaykm** [comment]
The exception stack indicates `JBoxDefaultPackagesVol.CURRENT_BUNDLE` is `None`.
That's possible if there's some issue in configuration or building of the package bundles.
Probably there would be some prior logs that point to the real issue.
