### ISSUE TITLE
erro clone project

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaLang/JuliaBox#418]
Server error: Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/IPython/html/base/handlers.py", line 441, in wrapper result = yield gen.maybe_future(method(self, *args, **kwargs)) File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run value = future.result() File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result raise_exc_info(self._exc_info) File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper yielded = next(result) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/handlers.py", line 123, in get path=path, type=type, format=format, content=content, File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/filemanager.py", line 347, in get model = self._dir_model(path, content=content) File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/contents/filemanager.py", line 248, in _dir_model os_path = os.path.join(os_dir, name) File "/usr/lib/python2.7/posixpath.py", line 80, in join path += '/' + b UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

**Comment by jmarcellopereira** [comment]
?

**Comment by jmarcellopereira** [comment]
I solved thus:
no rename your notebooks with ~,`, ç , ^, '  ;)
